name: Build and publish

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Type of version bump for this release."
        required: true
        options:
          - patch
          - minor
          - major
          - none

jobs:
  build_and_publish:
    uses: infinitaslearning/workflow-publish-public-module/.github/workflows/publish-module.yaml@v1
    with:
      version: ${{ inputs.version }}
    secrets: 
      NPMJS_ILPT_PUBLISH: ${{ secrets.NPMJS_ILPT_PUBLISH }}
